# Generated by Django 4.1.6 on 2023-02-15 01:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='nome')),
                ('description', models.CharField(max_length=50, verbose_name='descricao')),
                ('abrigo', models.CharField(max_length=5, verbose_name='abrigo')),
                ('aceitacao', models.CharField(max_length=5, verbose_name='aceitaçao')),
                ('ad_infra', models.CharField(max_length=5, verbose_name='infraestrutura')),
                ('ar_condicionado', models.CharField(max_length=5, verbose_name='ar_condicionado')),
                ('aut_pmmg', models.CharField(max_length=5, verbose_name='autorizacao_pmmg')),
                ('bbm', models.CharField(max_length=8, verbose_name='batalhao')),
                ('cob', models.CharField(max_length=8, verbose_name='cob')),
                ('convenio', models.CharField(max_length=5, verbose_name='convenio')),
                ('energia_cedida', models.CharField(max_length=5, verbose_name='energia')),
                ('fracao', models.CharField(max_length=30, verbose_name='fracao')),
                ('instalado', models.CharField(max_length=5, verbose_name='instalado')),
                ('inst_conf_enl', models.CharField(max_length=5, verbose_name='instalacao_configuracao_enlace')),
                ('inst_conf_rep', models.CharField(max_length=5, verbose_name='instalacao_configuracao_repetidora')),
                ('inst_gab', models.CharField(max_length=5, verbose_name='instalacao_gabinete')),
                ('inst_sis_irr', models.CharField(max_length=5, verbose_name='instal_sistema_radiante')),
                ('latitude', models.CharField(max_length=15, verbose_name='latitude')),
                ('laudo', models.CharField(max_length=5, verbose_name='laudo')),
                ('lic_anatel', models.CharField(max_length=5, verbose_name='licenca_anatel')),
                ('longitude', models.CharField(max_length=15, verbose_name='longitude')),
                ('nec_abrigo', models.CharField(max_length=5, verbose_name='abrigo')),
                ('obs', models.CharField(max_length=100, verbose_name='observacoes')),
                ('padrão', models.CharField(max_length=6, verbose_name='padrao')),
                ('propriedade', models.CharField(max_length=20, verbose_name='propriedade')),
                ('prospeccao', models.CharField(max_length=8, verbose_name='prospeccao')),
                ('pte', models.CharField(max_length=8, verbose_name='projeto_tecnico_executivo')),
                ('resp_nome', models.CharField(max_length=20, verbose_name='responsavel_nome')),
                ('resp_tel', models.CharField(max_length=15, verbose_name='responsavel_telefone')),
                ('seguranca', models.CharField(max_length=50, verbose_name='seguranca')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
