# Generated by Django 4.1.6 on 2023-02-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torre',
            name='description',
            field=models.CharField(max_length=950, verbose_name='descricao'),
        ),
    ]
