# Generated by Django 4.1.6 on 2023-02-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torres', '0002_alter_torre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torre',
            name='obs',
            field=models.CharField(max_length=200, verbose_name='observacoes'),
        ),
    ]
