# Generated by Django 4.1.6 on 2023-02-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torres', '0006_alter_torre_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torre',
            name='resp_nome',
            field=models.CharField(max_length=70, verbose_name='responsavel_nome'),
        ),
        migrations.AlterField(
            model_name='torre',
            name='resp_tel',
            field=models.CharField(max_length=70, verbose_name='responsavel_telefone'),
        ),
    ]
