# Generated by Django 4.1.6 on 2023-02-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torres', '0010_alter_torre_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torre',
            name='energia_cedida',
            field=models.CharField(max_length=25, verbose_name='energia'),
        ),
    ]
