# Generated by Django 4.1.6 on 2023-02-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torres', '0012_alter_torre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torre',
            name='propriedade',
            field=models.CharField(max_length=150, verbose_name='propriedade'),
        ),
        migrations.AlterField(
            model_name='torre',
            name='pte',
            field=models.CharField(max_length=50, verbose_name='projeto_tecnico_executivo'),
        ),
        migrations.AlterField(
            model_name='torre',
            name='resp_nome',
            field=models.CharField(max_length=170, verbose_name='responsavel_nome'),
        ),
        migrations.AlterField(
            model_name='torre',
            name='resp_tel',
            field=models.CharField(max_length=170, verbose_name='responsavel_telefone'),
        ),
        migrations.AlterField(
            model_name='torre',
            name='seguranca',
            field=models.CharField(max_length=300, verbose_name='seguranca'),
        ),
    ]
